from proxyml.client import (
    put_schema,
    synthesize_data,
    train_surrogate,
    predict,
    predict_batch,
    find_counterfactual,
    find_counterfactuals,
    interpret_counterfactual,
    get_feature_importances,
    get_model_summary,
    diff_models,
    list_models,
    delete_model,
)
from proxyml.schema import (
    get_schema,
    gen_continuous_schema,
    gen_categorical_schema,
    gen_discrete_schema,
)

__all__ = [
    "put_schema",
    "synthesize_data",
    "train_surrogate",
    "predict",
    "predict_batch",
    "find_counterfactual",
    "find_counterfactuals",
    "interpret_counterfactual",
    "get_feature_importances",
    "get_model_summary",
    "diff_models",
    "list_models",
    "delete_model",
    "get_schema",
    "gen_continuous_schema",
    "gen_categorical_schema",
    "gen_discrete_schema",
]
